# Generated by Django 6.1 on 2026-08-17 09:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Denomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(db_index=True, help_text='Human-facing product code entered on the billing form, e.g. SKU-1001.', max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('available_stock', models.PositiveIntegerField(default=0)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price of a single unit, before tax.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tax_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Tax percentage applied to this product, e.g. 18.00 for 18%.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email', models.EmailField(db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_price_without_tax', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_tax_payable', models.DecimalField(decimal_places=2, max_digits=14)),
                ('net_price', models.DecimalField(decimal_places=2, help_text='total_price_without_tax + total_tax_payable', max_digits=14)),
                ('rounded_net_price', models.DecimalField(decimal_places=2, help_text='net_price rounded DOWN to the nearest whole currency unit.', max_digits=14)),
                ('cash_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_amount', models.DecimalField(decimal_places=2, help_text='cash_paid - rounded_net_price', max_digits=14)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_error', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BalanceDenomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination_value', models.PositiveIntegerField()),
                ('count', models.PositiveIntegerField()),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_denominations', to='billing.purchase')),
            ],
            options={
                'ordering': ['-denomination_value'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id_snapshot', models.CharField(max_length=64)),
                ('product_name_snapshot', models.CharField(max_length=255)),
                ('unit_price_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_percentage_snapshot', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='unit_price_snapshot * quantity', max_digits=14)),
                ('tax_payable', models.DecimalField(decimal_places=2, help_text='purchase_price * tax_percentage_snapshot / 100', max_digits=14)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='purchase_price + tax_payable', max_digits=14)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_items', to='billing.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='billing.purchase')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
